### ISSUE TITLE
ModuleNotFoundError: No module named '_pynini'，请教用win10运行的大佬们，没有更改pynini任何东西，为啥报这个错？

### ISSUE THREAD

**Issue by GitUMini** [2noise/ChatTTS#147]
INFO:ChatTTS.core:Load from local: ./ChatTTS
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
INFO:ChatTTS.core:gpt loaded.
INFO:ChatTTS.core:decoder loaded.
INFO:ChatTTS.core:tokenizer loaded.
INFO:ChatTTS.core:All initialized.
INFO:ChatTTS.core:All initialized.
Traceback (most recent call last):
  File "E:\Python310\lib\idlelib\run.py", line 578, in runcode
    exec(code, self.locals)
  File "D:\IDM Download\ChatTTS-main\test.py", line 10, in <module>
    wavs = chat.infer(texts, use_decoder=True)
  File "D:\IDM Download\ChatTTS-main\ChatTTS\core.py", line 145, in infer
    self.init_normalizer(_lang)
  File "D:\IDM Download\ChatTTS-main\ChatTTS\core.py", line 182, in init_normalizer
    from nemo_text_processing.text_normalization.normalize import Normalizer
  File "E:\Anaconda3/Lib/site-packages\nemo_text_processing\text_normalization\__init__.py", line 15, in <module>
    from nemo_text_processing.text_normalization.normalize import Normalizer
  File "E:\Anaconda3/Lib/site-packages\nemo_text_processing\text_normalization\normalize.py", line 28, in <module>
    import pynini
  File "E:\Anaconda3/Lib/site-packages\pynini\__init__.py", line 1, in <module>
    from _pynini import *
ModuleNotFoundError: No module named '_pynini'

![微信截图_20240531232152](https://github.com/2noise/ChatTTS/assets/29656860/042c99d1-f703-4f4e-9c73-a68a8e1f09cb)
<img width="536" alt="微信图片_20240531232135" src="https://github.com/2noise/ChatTTS/assets/29656860/a28caeeb-0733-4fb8-b707-ef10ea903d76">

**Comment by GitUMini** [comment]
如果把“from _pynini import *”改为“from pynini import *”，又会提示“AttributeError: module 'pynini' has no attribute 'FstLike'”。

**Comment by jianchang512** [comment]
试试将代码中的 `chat.load_models(` 里加个参数改为  `chat.load_models(device="cpu")`

**Comment by ifredom** [comment]
这个不能商用，低模加了高噪音，散了吧
