### ISSUE TITLE
这个报错是怎么回事

### ISSUE THREAD

**Issue by iscc-top** [2noise/ChatTTS#155]
To create a public link, set `share=True` in `launch()`.
INFO:ChatTTS.core:All initialized.
WARNING:ChatTTS.core:Package WeTextProcessing not found!                         Run: conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing
Traceback (most recent call last):
  File "C:\Users\20514\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20514\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20514\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1945, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20514\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20514\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20514\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\20514\AppData\Local\Programs\Python\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\20514\AppData\Local\Programs\Python\Python311\Lib\site-packages\gradio\utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "d:\桌面\ChatTTS-main\webui.py", line 35, in generate_audio
    text = chat.infer(text,
          ^^^^^^^^^^^^^^^^^
  File "d:\桌面\ChatTTS-main\ChatTTS\core.py", line 146, in infer
    self.init_normalizer(_lang)
  File "d:\桌面\ChatTTS-main\ChatTTS\core.py", line 192, in init_normalizer
    self.normalizer[lang] = Normalizer().normalize
                            ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'Normalizer' where it is not associated with a value

**Comment by randy-tsukemen** [comment]
conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing

**Comment by Oliver-Lief** [comment]
我也是，按提示执行安装那两个包不成功

**Comment by roywei** [comment]
pip install nemo_text_processing

**Comment by zhengpenghu** [comment]
> conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing

This solved the bug on my M1 pro macbook.
