### ISSUE TITLE
OSError: [WinError 126] 找不到指定的模块。 Error loading 

### ISSUE THREAD

**Issue by xinyang111** [2noise/ChatTTS#156]
Traceback (most recent call last):
  File "e:\Python\ChatTTS-main\test.py", line 1, in <module>
    import ChatTTS
  File "e:\Python\ChatTTS-main\ChatTTS\__init__.py", line 1, in <module>
    from .core import Chat
  File "e:\Python\ChatTTS-main\ChatTTS\core.py", line 6, in <module>
    import torch
  File "C:\Users\xingz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "C:\Users\xingz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torch\lib\shm.dll" or one of its dependencies.

**Comment by anitman** [comment]
切换python 3.11以及以下的版本，建议主要是3.11或3.10，3.12有很多项目都不兼容。

**Comment by xinyang111** [comment]
感觉不是版本的问题，切换了 3.11 3.10 都出现这个问题，不知道啥情况
Traceback (most recent call last):
  File "e:\Python\ChatTTS-main\test.py", line 1, in <module>
    import ChatTTS
  File "e:\Python\ChatTTS-main\ChatTTS\__init__.py", line 1, in <module>
    from .core import Chat
  File "e:\Python\ChatTTS-main\ChatTTS\core.py", line 6, in <module>
    import torch
  File "C:\Users\xingz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "C:\Users\xingz\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\lib\shm.dll" or one of its dependencies.

**Comment by shirubei** [comment]
Python 3.10 同样问题。

**Comment by xinyang111** [comment]
是的 ，Python 3.11  Python 3.10 我都测试过了，不行，我用的 win11系统

**Comment by shirubei** [comment]
会不会是pytorch本身的问题啊，看出错就是在它的init里面

**Comment by shirubei** [comment]
> 是的 ，Python 3.11 Python 3.10 我都测试过了，不行，我用的 win11系统

把Pytorch 2.3版卸载了，装2.2.2，就不会出现 shm.dll 无法加载的问题。我是用的cu118，所以用以下命令

pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118

**Comment by sunqb** [comment]
> > 是的 ，Python 3.11 Python 3.10 我都测试过了，不行，我用的 win11系统
> 
> 把Pytorch 2.3版卸载了，装2.2.2，就不会出现 shm.dll 无法加载的问题。我是用的cu118，所以用以下命令
> 
> pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118

这个可以的

**Comment by zky001** [comment]
> > 是的 ，Python 3.11 Python 3.10 我都测试过了，不行，我用的 win11系统
> 
> 把Pytorch 2.3版卸载了，装2.2.2，就不会出现 shm.dll 无法加载的问题。我是用的cu118，所以用以下命令
> 
> pip install torch==2.2.2 torchvision==0.17.2 torchaudio==2.2.2 --index-url https://download.pytorch.org/whl/cu118

我试了不行，装vllm的时候
![image](https://github.com/2noise/ChatTTS/assets/9131265/898ea78c-66fe-4135-b263-0b71f00b74ca)

![image](https://github.com/2noise/ChatTTS/assets/9131265/ab0ef6c0-5712-479f-aebc-b03f5240f91c)
