### ISSUE TITLE
启动运行报错 ，下载安装是提示：客户端没有执行权限，然后dvae.yaml缺少了

### ISSUE THREAD

**Issue by TeachCourse** [2noise/ChatTTS#189]
loading ChatTTS model...
INFO:ChatTTS.core:Load from cache: C:\Users\zhaolin/.cache/huggingface\hub/models--2Noise--ChatTTS/snapshots\ce5913842aebd78e4a01a02d47244b8d62ac4ee3
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use CPU instead
INFO:ChatTTS.core:use cpu
INFO:ChatTTS.core:vocos loaded.
Traceback (most recent call last):
  File "E:\pythonProject\open_project\ChatTTS\webui.py", line 113, in <module>
    main()
  File "E:\pythonProject\open_project\ChatTTS\webui.py", line 104, in main
    chat.load_models()
  File "E:\pythonProject\open_project\ChatTTS\ChatTTS\core.py", line 62, in load_models
    self._load(**{k: os.path.join(download_path, v) for k, v in OmegaConf.load(os.path.join(download_path, 'config', 'path.yaml')).items()}, **kwargs)
  File "E:\pythonProject\open_project\ChatTTS\ChatTTS\core.py", line 90, in _load
    cfg = OmegaConf.load(dvae_config_path)
  File "E:\pythonProject\open_project\ChatTTS\venv\lib\site-packages\omegaconf\omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\zhaolin\\.cache\\huggingface\\hub\\models--2Noise--ChatTTS\\snapshots\\ce5913842aebd78e4a01a02d47244b8d62ac4ee3\
\config\\dvae.yaml'

**Comment by ThankVinci** [comment]
从https://huggingface.co/2Noise/ChatTTS/tree/main/config下载dvae.yaml ,手动复制到目标目录可以解决，不然就等修复咯
