### ISSUE TITLE
无法运行?

### ISSUE THREAD

**Issue by iwaitu** [2noise/ChatTTS#198]
```
(chattts) iwaitu@DESKTOP-RDS3VMA:~/work/chatTTS$ python webui.py
Traceback (most recent call last):
  File "/mnt/d/WSLData/chatTTS/webui.py", line 9, in <module>
    import ChatTTS
  File "/mnt/d/WSLData/chatTTS/ChatTTS/__init__.py", line 1, in <module>
    from .core import Chat
  File "/mnt/d/WSLData/chatTTS/ChatTTS/core.py", line 8, in <module>
    from vocos import Vocos
  File "/home/iwaitu/anaconda3/envs/chattts/lib/python3.10/site-packages/vocos/__init__.py", line 1, in <module>
    from vocos.pretrained import Vocos
  File "/home/iwaitu/anaconda3/envs/chattts/lib/python3.10/site-packages/vocos/pretrained.py", line 9, in <module>
    from vocos.feature_extractors import FeatureExtractor, EncodecFeatures
  File "/home/iwaitu/anaconda3/envs/chattts/lib/python3.10/site-packages/vocos/feature_extractors.py", line 4, in <module>
    import torchaudio
  File "/home/iwaitu/anaconda3/envs/chattts/lib/python3.10/site-packages/torchaudio/__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
  File "/home/iwaitu/anaconda3/envs/chattts/lib/python3.10/site-packages/torchaudio/_extension/__init__.py", line 38, in <module>
    _load_lib("libtorchaudio")
  File "/home/iwaitu/anaconda3/envs/chattts/lib/python3.10/site-packages/torchaudio/_extension/utils.py", line 60, in _load_lib
    torch.ops.load_library(path)
  File "/home/iwaitu/anaconda3/envs/chattts/lib/python3.10/site-packages/torch/_ops.py", line 852, in load_library
    ctypes.CDLL(path)
  File "/home/iwaitu/anaconda3/envs/chattts/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/iwaitu/anaconda3/envs/chattts/lib/python3.10/site-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZN3c104impl3cow11cow_deleterEPv
```

运行出现错误

**Comment by WJRye** [comment]
同出现这个

**Comment by WJRye** [comment]
reinstall torchaudio can fix this bug.

1. pip3 unstall torchaudio
2. pip3 install torchaudio
