### ISSUE TITLE
Normalizer reference before assignment

### ISSUE THREAD

**Issue by iplayfast** [2noise/ChatTTS#270]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chris/ai/tts/ChatTTS/ChatTTS/core.py", line 146, in infer
    self.init_normalizer(_lang)
  File "/home/chris/ai/tts/ChatTTS/ChatTTS/core.py", line 199, in init_normalizer
    self.normalizer[lang] = partial(Normalizer(input_case='cased', lang=lang).normalize, verbose=False, punct_post_process=True)
UnboundLocalError: local variable 'Normalizer' referenced before assignment

**Comment by libukai** [comment]
```bash
conda install -c conda-forge pynini=2.1.5 && pip install nemo_text_processing
```

缺少相关依赖，请按照官方代码中的指引安装

**Comment by like-yo** [comment]
找到chatTTS的core.py的143行到149行注释掉

**Comment by jeffscottward** [comment]
╰─ $ conda install -c conda-forge pynini=2.1.5 && pip install nemo_text_processing
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: | warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package pynini-2.1.5-py312h389731b_6 requires libcxx >=15.0.7, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ libcxx 14.0.6.*  is requested and can be installed;
├─ pin-1 is installable and it requires
│  └─ python 3.12.* , which can be installed;
└─ pynini 2.1.5**  is not installable because there are no viable options
   ├─ pynini 2.1.5 would require
   │  └─ libcxx >=15.0.7 , which conflicts with any installable versions previously reported;
   ├─ pynini 2.1.5 would require
   │  └─ python >=3.10,<3.11.0a0 *_cpython, which conflicts with any installable versions previously reported;
   ├─ pynini 2.1.5 would require
   │  └─ python >=3.11,<3.12.0a0 *_cpython, which conflicts with any installable versions previously reported;
   ├─ pynini 2.1.5 would require
   │  └─ python >=3.8,<3.9.0a0 *_cpython, which conflicts with any installable versions previously reported;
   └─ pynini 2.1.5 would require
      └─ python >=3.9,<3.10.0a0 *_cpython, which conflicts with any installable versions previously reported.
