### ISSUE TITLE
服务启动了，但是点击生成语音时出错了，并且from tn.chinese.normalizer import Normalizer显示没有tn模块，请问tn模块怎么下载

### ISSUE THREAD

**Issue by wzl-GitHubs** [2noise/ChatTTS#320]
Running on local URL:  http://0.0.0.0:8089
INFO:httpx:HTTP Request: GET http://localhost:8089/startup-events "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: HEAD http://localhost:8089/ "HTTP/1.1 200 OK"
INFO:httpx:HTTP Request: GET https://api.gradio.app/v2/tunnel-request "HTTP/1.1 200 OK"
Running on public URL: https://e7859ed07854cdd0de.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
INFO:ChatTTS.core:All initialized.
WARNING:ChatTTS.core:Package WeTextProcessing not found!                         Run: conda install -c conda-forge pynini=2.1.5 && pip install WeTextProcessing
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\ChatTTS\lib\site-packages\gradio\queueing.py", line 532, in process_events
    response = await route_utils.call_process_api(
  File "D:\ProgramData\Anaconda3\envs\ChatTTS\lib\site-packages\gradio\route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\ProgramData\Anaconda3\envs\ChatTTS\lib\site-packages\gradio\blocks.py", line 1928, in process_api
    result = await self.call_function(
  File "D:\ProgramData\Anaconda3\envs\ChatTTS\lib\site-packages\gradio\blocks.py", line 1514, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\ProgramData\Anaconda3\envs\ChatTTS\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\ProgramData\Anaconda3\envs\ChatTTS\lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "D:\ProgramData\Anaconda3\envs\ChatTTS\lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "D:\ProgramData\Anaconda3\envs\ChatTTS\lib\site-packages\gradio\utils.py", line 832, in wrapper
    response = f(*args, **kwargs)
  File "E:\ChatTTS-main\webui.py", line 34, in generate_audio
    text = chat.infer(text,
  File "E:\ChatTTS-main\ChatTTS\core.py", line 146, in infer
    self.init_normalizer(_lang)
  File "E:\ChatTTS-main\ChatTTS\core.py", line 193, in init_normalizer
    self.normalizer[lang] = Normalizer().normalize
UnboundLocalError: local variable 'Normalizer' referenced before assignment

**Comment by jianchang512** [comment]
#164

**Comment by albertyann** [comment]
根据#164 的结论，基本上可以放弃 windows，依赖的一个库暂时不支持windows。也可以不使用该库，只是效果降级很多

**Comment by jianchang512** [comment]
windows也可以用，不过必须用 conda install 安装，也就是需要用conda 管理环境依赖
