### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for GPT_warpper

### ISSUE THREAD

**Issue by GarrickLin** [2noise/ChatTTS#43]
```
INFO:ChatTTS.core:Load from cache: /Users/garrick/.cache/huggingface/hub/models--2Noise--ChatTTS/snapshots/f75c0b89484b01436b422debba01e276c8f6de84
WARNING:ChatTTS.utils.gpu_utils:No GPU found, use MPS instead
INFO:ChatTTS.core:use mps
INFO:ChatTTS.core:vocos loaded.
INFO:ChatTTS.core:dvae loaded.
Traceback (most recent call last):
  File "/Users/garrick/workspace/python/ChatTTS/test1.py", line 5, in <module>
    chat.load_models()
  File "/Users/garrick/workspace/python/ChatTTS/ChatTTS/core.py", line 55, in load_models
    self._load(**{k: os.path.join(download_path, v) for k, v in OmegaConf.load(os.path.join(download_path, 'config', 'path.yaml')).items()})
  File "/Users/garrick/workspace/python/ChatTTS/ChatTTS/core.py", line 96, in _load
    gpt.load_state_dict(torch.load(gpt_ckpt_path, map_location='cpu'))
  File "/Users/garrick/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GPT_warpper:
        Missing key(s) in state_dict: "head_text.weight_g", "head_text.weight_v", "head_code.0.weight_g", "head_code.0.weight_v", "head_code.1.weight_g", "head_code.1.weight_v", "head_code.2.weight_g", "head_code.2.weight_v", "head_code.3.weight_g", "head_code.3.weight_v". 
        Unexpected key(s) in state_dict: "head_text.parametrizations.weight.original0", "head_text.parametrizations.weight.original1", "head_code.0.parametrizations.weight.original0", "head_code.0.parametrizations.weight.original1", "head_code.1.parametrizations.weight.original0", "head_code.1.parametrizations.weight.original1", "head_code.2.parametrizations.weight.original0", "head_code.2.parametrizations.weight.original1", "head_code.3.parametrizations.weight.original0", "head_code.3.parametrizations.weight.original1". 
```

**Comment by neverbiasu** [comment]
this error says the model's key is not as expected, I guessed if it caused by the solution of  #46  
I fix that issues by change `from torch.nn.utils.parametrizations import weight_norm` to `from torch.nn.utilsimport weight_norm`, is these weight_norm the same?
👀 waiting...

**Comment by GarrickLin** [comment]
yeah，I've changed the code in `gpt.py`
```
# from torch.nn.utils.parametrizations import weight_norm
from torch.nn.utils import weight_norm
```

**Comment by GarrickLin** [comment]
> yeah，I've changed the code in `gpt.py`
> 
> ```
> # from torch.nn.utils.parametrizations import weight_norm
> from torch.nn.utils import weight_norm
> ```

no need to change this code if you upgrade pytorch to 2.3.0, or you will suffer an error like "RuntimeError: Error(s) in loading state_dict for GPT_warpper"

**Comment by cucdengjunli** [comment]
mark
