### ISSUE TITLE
大佬们，我这是啥问题，安装没有安装上

### ISSUE THREAD

**Issue by youyongba** [2noise/ChatTTS#456]
pip3 install git+https://github.com/2noise/ChatTTS@main
Collecting git+https://github.com/2noise/ChatTTS@main
  Cloning https://github.com/2noise/ChatTTS (to revision main) to /private/var/folders/0h/ms_ff8y1495gxn363n22bbv40000gn/T/pip-req-build-1jrbde7l
  Running command git clone --filter=blob:none --quiet https://github.com/2noise/ChatTTS /private/var/folders/0h/ms_ff8y1495gxn363n22bbv40000gn/T/pip-req-build-1jrbde7l
  Resolved https://github.com/2noise/ChatTTS to commit b9d6cd210c6aa44ef811f95fc672737840801e1d
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/0h/ms_ff8y1495gxn363n22bbv40000gn/T/pip-build-env-u6n9142o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/private/var/folders/0h/ms_ff8y1495gxn363n22bbv40000gn/T/pip-build-env-u6n9142o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/0h/ms_ff8y1495gxn363n22bbv40000gn/T/pip-build-env-u6n9142o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/0h/ms_ff8y1495gxn363n22bbv40000gn/T/pip-build-env-u6n9142o/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
        File "/private/var/folders/0h/ms_ff8y1495gxn363n22bbv40000gn/T/pip-build-env-u6n9142o/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/0h/ms_ff8y1495gxn363n22bbv40000gn/T/pip-build-env-u6n9142o/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 146, in setup
          _setup_distribution = dist = klass(attrs)
        File "/private/var/folders/0h/ms_ff8y1495gxn363n22bbv40000gn/T/pip-build-env-u6n9142o/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 320, in __init__
          self.metadata.version = self._normalize_version(self.metadata.version)
        File "/private/var/folders/0h/ms_ff8y1495gxn363n22bbv40000gn/T/pip-build-env-u6n9142o/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 356, in _normalize_version
          normalized = str(Version(version))
        File "/private/var/folders/0h/ms_ff8y1495gxn363n22bbv40000gn/T/pip-build-env-u6n9142o/overlay/lib/python3.10/site-packages/setuptools/_vendor/packaging/version.py", line 200, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'develop'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by fumiama** [comment]
再试试。
