### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by ccj** [2noise/ChatTTS#500]
Loading ChatTTS model...
Traceback (most recent call last):
  File "/Users/ccj/Desktop/project/ChatTTS_colab/webui_mix.py", line 46, in <module>
    chat = load_chat_tts_model(source=args.source, local_path=args.local_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ccj/Desktop/project/ChatTTS_colab/tts_model.py", line 25, in load_chat_tts_model
    chat.load_models(source=source, force_redownload=force_redownload, custom_path=local_path, compile=False)
TypeError: Chat.load_models() got an unexpected keyword argument 'custom_path'

**Comment by fumiama** [comment]
duplicate with #490
