### ISSUE TITLE
 soundfile_backend.save got error 2D Tensor, got 1D.

### ISSUE THREAD

**Issue by shaofanqi** [2noise/ChatTTS#561]
使用demo时候出现下列错误，求解呀

text:   3%|██▊                                                                                                           | 10/384(max) [00:00, 20.41it/s]
code:   3%|██▉                                                                                                          | 56/2048(max) [00:01, 55.59it/s]
Traceback (most recent call last):
  File "/testTTs.py", line 12, in <module>
    torchaudio.save("output1.wav", torch.from_numpy(wavs[0]), 24000)
  File "/miniconda3/envs/llm/lib/python3.11/site-packages/torchaudio/_backend/utils.py", line 313, in save
    return backend.save(
           ^^^^^^^^^^^^^
  File "/miniconda3/envs/llm/lib/python3.11/site-packages/torchaudio/_backend/soundfile.py", line 44, in save
    soundfile_backend.save(
  File "/miniconda3/envs/llm/lib/python3.11/site-packages/torchaudio/_backend/soundfile_backend.py", line 427, in save
    raise ValueError(f"Expected 2D Tensor, got {src.ndim}D.")
ValueError: Expected 2D Tensor, got 1D.

**Comment by panpan123456** [comment]
mark

**Comment by fumiama** [comment]
文档还未同步更新。

**Comment by xipingL** [comment]
> 文档还未同步更新。

你好 请问目前更新了吗 我现在还是有这个问题

**Comment by fumiama** [comment]
> > 文档还未同步更新。
> 
> 你好 请问目前更新了吗 我现在还是有这个问题

最新文档见 https://github.com/2noise/ChatTTS/tree/dev?tab=readme-ov-file#basic-usage

**Comment by fumiama** [comment]
> > 文档还未同步更新。
> 
> 你好 请问目前更新了吗 我现在还是有这个问题

最新文档见 https://github.com/2noise/ChatTTS/tree/dev?tab=readme-ov-file#basic-usage

**Comment by sipie800** [comment]
+1
