### ISSUE TITLE
No module named 'tokenizers'

### ISSUE THREAD

**Issue by lukeewin** [2noise/ChatTTS#566]
My operating environment is：
1. Python: 3.9
2. OS: Windows 11
3. transformers: 4.42.4
4. tokenizers: 0.19.1
5. ChatTTS: 0.1.1

When I run the program, it reports the error "No module named 'tokenizers'".
Here is the specific error information I encountered:
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Works\Python\tts\ChatTTS\examples\web\webui.py", line 13, in <module>
    from examples.web.funcs import *
  File "D:\Works\Python\tts\ChatTTS\examples\web\funcs.py", line 16, in <module>
    import ChatTTS
  File "D:\Software\office\python\Anaconda\envs\chattts\lib\site-packages\ChatTTS\__init__.py", line 1, in <module>
    from .core import Chat
  File "D:\Software\office\python\Anaconda\envs\chattts\lib\site-packages\ChatTTS\core.py", line 18, in <module>
    from .model import DVAE, GPT, gen_logits
  File "D:\Software\office\python\Anaconda\envs\chattts\lib\site-packages\ChatTTS\model\__init__.py", line 2, in <module>
    from .gpt import GPT
  File "D:\Software\office\python\Anaconda\envs\chattts\lib\site-packages\ChatTTS\model\gpt.py", line 19, in <module>
    from transformers import LlamaModel, LlamaConfig, LogitsWarper
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "D:\Software\office\python\Anaconda\envs\chattts\lib\site-packages\transformers\utils\import_utils.py", line 1558, in __getattr__
    value = getattr(module, name)
  File "D:\Software\office\python\Anaconda\envs\chattts\lib\site-packages\transformers\utils\import_utils.py", line 1557, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\Software\office\python\Anaconda\envs\chattts\lib\site-packages\transformers\utils\import_utils.py", line 1569, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
Failed to import transformers.integrations.ggml because of the following error (look up to see its traceback):
No module named 'tokenizers'

Can you help me? How to deal with the error?

**Comment by fumiama** [comment]
不要安装tokenizers包，本项目没有依赖它的位置。

**Comment by lukeewin** [comment]
> 不要安装tokenizers包，本项目没有依赖它的位置。ChatTTS如果使用GitHub下载的仓库，则无需pip安装ChatTTS包。这两个包如已安装，请卸载后再试。

Thank your, I've already solved it. This is due to the version of transformers. Lowering the version resolved the issue.
