### ISSUE TITLE
Python pip install chattts  but error  panic: The handle is invalid.

### ISSUE THREAD

**Issue by Jacky1y** [2noise/ChatTTS#620]
```
pip install chattts
```

but error
```
panic: The handle is invalid.**

goroutine 1 [running]:
rvcmd/console.init.0()
	rvcmd/console/console_windows.go:46 +0x1d4
download to local path D:\1 yangzhen\make video failed.
vocos not initialized.
gpt not initialized.
tokenizer not initialized.
decoder not initialized.
Traceback (most recent call last):
  File "py", line 22, in <module>
    wavs = chat.infer(texts)
  File "\lib\site-packages\ChatTTS\core.py", line 242, in infer
    return next(res_gen)
  File \lib\site-packages\ChatTTS\core.py", line 360, in _infer
    assert self.has_loaded(use_decoder=use_decoder)
AssertionError
```

**Comment by fumiama** [comment]
请勿在IDE中直接点击运行。
