### ISSUE TITLE
[Bug/unclear requirements]UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by hgftrdw45ud67is8o89** [2noise/ChatTTS#657]
anyone project dev can share their cudnn version and their torch config?

`python -m torch.utils.collect_env`

it keeps crashing
`\site-packages\torch\nn\modules\conv.py:306: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at ..\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return F.conv1d(input, weight, bias, self.stride,
Traceback (most recent call last):
  File "............\Chattts_adv.py", line 34, in <module>
    torchaudio.save("self_introduction_output.wav", torch.from_numpy(audio_array_en[0]), 24000)
  File ",.........\Lib\site-packages\torchaudio\_backend\utils.py", line 313, in save
    return backend.save(
           ^^^^^^^^^^^^^
  File ",...................\Lib\site-packages\torchaudio\_backend\soundfile.py", line 44, in save
    soundfile_backend.save(
  File ",,,,,,,,,,,,,,,,,,,,,,,,,,,\Lib\site-packages\torchaudio\_backend\soundfile_backend.py", line 427, in save
    raise ValueError(f"Expected 2D Tensor, got {src.ndim}D.")
ValueError: Expected 2D Tensor, got 1D.`

**Comment by fumiama** [comment]
ref #635, maybe the `unsqueeze` issue.

**Comment by hgftrdw45ud67is8o89** [comment]
you are right,but the cudnn error is there,can you share your config,or if use g can try to dump the config, kinda funny to always have that cudnn error.

**Comment by fumiama** [comment]
> you are right,but the cudnn error is there,can you share your config,or if use g can try to dump the config, kinda funny to always have that cudnn error.

Actually the original code works in many cases, but will throw error on some platform. This is quite strange so we're now figuring it out.
