### ISSUE TITLE
Expected 2D Tensor, got 1D.

### ISSUE THREAD

**Issue by LerroyJ** [2noise/ChatTTS#665]
found invalid characters: {'1'}
found invalid characters: {'2'}
text:   0%|                                                                                        | 0/384(max) [00:00, ?it/s]We detected that you are passing `past_key_values` as a tuple and this is deprecated and will be removed in v4.43. Please use an appropriate `Cache` class (https://huggingface.co/docs/transformers/v4.41.3/en/internal/generation_utils#transformers.Cache)
text:   3%|██▏                                                                                | 10/384(max) [00:01,  8.05it/s]
code:   4%|███▏                                                                              | 79/2048(max) [00:05, 13.71it/s]
Traceback (most recent call last):
  File "D:\GithubProject\ChatTTS\examples\cmd\cc.py", line 12, in <module>
    torchaudio.save("output1.wav", torch.from_numpy(wavs[0]), 24000)
  File "D:\codingTools\anaconda\envs\chattts\lib\site-packages\torchaudio\_backend\utils.py", line 313, in save
    return backend.save(
  File "D:\codingTools\anaconda\envs\chattts\lib\site-packages\torchaudio\_backend\soundfile.py", line 44, in save
    soundfile_backend.save(
  File "D:\codingTools\anaconda\envs\chattts\lib\site-packages\torchaudio\_backend\soundfile_backend.py", line 427, in save
    raise ValueError(f"Expected 2D Tensor, got {src.ndim}D.")
ValueError: Expected 2D Tensor, got 1D.

**Comment by LerroyJ** [comment]
修复了

**Comment by FeyaM** [comment]
我也遇到这个问题，请问是怎么修复的？

**Comment by soyh** [comment]
hey bro, how do you solve this issue?
