### ISSUE TITLE
官方示例运行不起来，求助

### ISSUE THREAD

**Issue by royallenppt** [2noise/ChatTTS#716]
运行Basic Usage报错如下
```
panic: The handle is invalid.

goroutine 1 [running]:
rvcmd/console.init.0()
	rvcmd/console/console_windows.go:46 +0x1d4
download to local path D:\codes\python_learn\chattts_learn failed.
vocos not initialized.
gpt not initialized.
tokenizer not initialized.
decoder not initialized.
Traceback (most recent call last):
  File "D:\codes\python_learn\chattts_learn\hello_world.py", line 10, in <module>
    wavs = chat.infer(texts)
           ^^^^^^^^^^^^^^^^^
  File "D:\developer\env\conda\envs\python311\Lib\site-packages\ChatTTS\core.py", line 242, in infer
    return next(res_gen)
           ^^^^^^^^^^^^^
  File "D:\developer\env\conda\envs\python311\Lib\site-packages\ChatTTS\core.py", line 360, in _infer
    assert self.has_loaded(use_decoder=use_decoder)
AssertionError
```
版本如下
```
torch                             2.2.2+cu121
torchaudio                        2.2.2+cu121
torchtext                         0.18.0
torchvision                       0.17.2+cu121
```

**Comment by neoyxm** [comment]
> 运行Basic Usage报错如下
> 
> panic: The handle is invalid.
> download to local path D:\codes\python_learn\chattts_learn failed.

模型下载失败了， 检查你的网络有没有问题，尤其是梯子。

**Comment by royallenppt** [comment]
好的谢谢！

**Comment by fumiama** [comment]
与 #620 重复。
