### ISSUE TITLE
RuntimeError: stft input and window must be on the same device but got self on cpu and window on cuda:0

### ISSUE THREAD

**Issue by CaptainDP** [2noise/ChatTTS#724]
系统环境：
ubuntu22

ChatTTS代码版本：
最新master和dev，都一样报错

使用方式：
webui.py上传Sample Audio时

报错信息：
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/queueing.py", line 521, in process_events
    response = await route_utils.call_process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1945, in process_api
    result = await self.call_function(
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/blocks.py", line 1513, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "/root/miniconda3/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/root/miniconda3/lib/python3.10/site-packages/gradio/utils.py", line 831, in wrapper
    response = f(*args, **kwargs)
  File "/root/ChatTTS/examples/web/funcs.py", line 121, in on_upload_sample_audio
    spk_smp = chat.sample_audio_speaker(sample_audio)
  File "/root/ChatTTS/ChatTTS/core.py", line 163, in sample_audio_speaker
    return self.speaker.encode_prompt(self.dvae.sample_audio(wav))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/ChatTTS/ChatTTS/model/dvae.py", line 292, in sample_audio
    return self(wav, "encode").squeeze_(0)
  File "/root/ChatTTS/ChatTTS/model/dvae.py", line 248, in __call__
    return super().__call__(inp, mode)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/ChatTTS/ChatTTS/model/dvae.py", line 255, in forward
    mel = self.preprocessor_mel(inp)
  File "/root/ChatTTS/ChatTTS/model/dvae.py", line 197, in __call__
    return super().__call__(audio)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/ChatTTS/ChatTTS/model/dvae.py", line 200, in forward
    mel: torch.Tensor = self.mel_spec(audio)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torchaudio/transforms/_transforms.py", line 619, in forward
    specgram = self.spectrogram(waveform)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torchaudio/transforms/_transforms.py", line 110, in forward
    return F.spectrogram(
  File "/root/miniconda3/lib/python3.10/site-packages/torchaudio/functional/functional.py", line 126, in spectrogram
    spec_f = torch.stft(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/functional.py", line 650, in stft
    return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
RuntimeError: stft input and window must be on the same device but got self on cpu and window on cuda:0

**Comment by bingyunsky** [comment]
dev版本 同样的问题

**Comment by fumiama** [comment]
与 #603 重复。将在近期修复。
