### ISSUE TITLE
Unable to generate output

### ISSUE THREAD

**Issue by Siigari** [2noise/ChatTTS#728]
When I add a sample audio, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "F:\ChatTTS\examples\web\funcs.py", line 118, in on_upload_sample_audio
    spk_smp = chat.sample_audio_speaker(sample_audio)
AttributeError: 'Chat' object has no attribute 'sample_audio_speaker'. Did you mean: 'sample_random_speaker'?
```

When I hit generate, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\route_utils.py", line 321, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\David\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "F:\ChatTTS\examples\web\funcs.py", line 147, in refine_text
    params_refine_text=ChatTTS.Chat.RefineTextParams(
TypeError: Chat.RefineTextParams.__init__() got an unexpected keyword argument 'manual_seed'
```

**Comment by fumiama** [comment]
try
```bash
pip uninstall ChatTTS
```
to remove old stable ChatTTS version.
