### ISSUE TITLE
[Bug] chattts-forge下，使用随机种子音色生成wav失败

### ISSUE THREAD

**Issue by zydmtaichi** [2noise/ChatTTS#749]
```
Traceback (most recent call last):
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/sdb/conda/envs/ChatTTS-Forge/lib/python3.10/site-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/sdb/ChatTTS-Forge/modules/webui/tts_tab.py", line 73, in tts_generate_with_history
    audio = tts_generate(model_id=self.model_id, *args, **kwargs)
  File "/mnt/sdb/ChatTTS-Forge/modules/webui/webui_utils.py", line 248, in tts_generate
    spk = ChatTtsModel.ChatTTSModel.create_speaker_from_seed(spk)
  File "/mnt/sdb/ChatTTS-Forge/modules/core/models/tts/ChatTtsModel.py", line 24, in create_speaker_from_seed
    token = chat._sample_random_speaker().float()
AttributeError: 'Chat' object has no attribute '_sample_random_speaker'. Did you mean: 'sample_random_speaker'?
```

**Comment by zydmtaichi** [comment]
环境 
python 3.10.14
torch 2.4.1+cu118

**Comment by fumiama** [comment]
第三方扩展库请找对应作者解决。
