### ISSUE TITLE
Issue with Basic Usage Code

### ISSUE THREAD

**Issue by effy46** [2noise/ChatTTS#775]
Here is the code I am using:
```py
import ChatTTS
import torch
import torchaudio


chat = ChatTTS.Chat()
chat.load(compile=False) # Set to True for better performance

texts = ["All set. Lets go", "Lets get started,drive safe"]

wavs = chat.infer(texts)

for i in range(len(wavs)):
    """
    In some versions of torchaudio, the first line works but in other versions, so does the second line.
    """
    try:
        torchaudio.save(f"basic_output{i}.wav", torch.from_numpy(wavs[i]).unsqueeze(0), 24000)
    except:
        torchaudio.save(f"basic_output{i}.wav", torch.from_numpy(wavs[i]), 24000)
```
I received below error:
```
e detected that you are passing `past_key_values` as a tuple of tuples. This is deprecated and will be removed in v4.47. Please convert your cache or use an appropriate `Cache` class (https://huggingface.co/docs/transformers/kv_cache#legacy-cache-format)
text:   3%|█████▋                                                                                                                                                                                | 12/384(max) [00:01,  6.15it/s]
code:   4%|███████▌                                                                                                                                                                             | 85/2048(max) [00:07, 10.64it/s]
Traceback (most recent call last):
  File "e:\Project\VoiceAI\ChatTTS\ChatTTS\sample.py", line 18, in <module>
    torchaudio.save(f"basic_output{i}.wav", torch.from_numpy(wavs[i]).unsqueeze(0), 24000)
  File "C:\Users\fiona\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torchaudio\_backend\utils.py", line 312, in save
    backend = dispatcher(uri, format, backend)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fiona\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torchaudio\_backend\utils.py", line 222, in dispatcher
    raise RuntimeError(f"Couldn't find appropriate backend to handle uri {uri} and format {format}.")
RuntimeError: Couldn't find appropriate backend to handle uri basic_output0.wav and format None.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\Project\VoiceAI\ChatTTS\ChatTTS\sample.py", line 20, in <module>
    torchaudio.save(f"basic_output{i}.wav", torch.from_numpy(wavs[i]), 24000)
  File "C:\Users\fiona\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torchaudio\_backend\utils.py", line 312, in save
    backend = dispatcher(uri, format, backend)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fiona\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\torchaudio\_backend\utils.py", line 222, in dispatcher
    raise RuntimeError(f"Couldn't find appropriate backend to handle uri {uri} and format {format}.")
RuntimeError: Couldn't find appropriate backend to handle uri basic_output0.wav and format None.
```

**Comment by fumiama** [comment]
Please put ffmpeg into PATH env variable.

**Comment by PandaXHFF** [comment]
panic: The handle is invalid.

goroutine 1 [running]:
rvcmd/console.init.0()
	rvcmd/console/console_windows.go:46 +0x1d4
download to local path E:\pycharm\pythonProject\.venv failed.
vocos not initialized.
gpt not initialized.
tokenizer not initialized.
embed not initialized.
decoder not initialized.
Traceback (most recent call last):
  File "E:\pycharm\pythonProject\.venv\测试.py", line 11, in <module>
    wavs = chat.infer(texts)
           ^^^^^^^^^^^^^^^^^
  File "E:\pycharm\pythonProject\.venv\Lib\site-packages\ChatTTS\core.py", line 220, in infer
    return next(res_gen)
           ^^^^^^^^^^^^^
  File "E:\pycharm\pythonProject\.venv\Lib\site-packages\ChatTTS\core.py", line 356, in _infer
    assert self.has_loaded(use_decoder=use_decoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by PandaXHFF** [comment]
panic: The handle is invalid.

goroutine 1 [running]:
rvcmd/console.init.0()
	rvcmd/console/console_windows.go:46 +0x1d4
download to local path E:\pycharm\pythonProject\.venv failed.
vocos not initialized.
gpt not initialized.
tokenizer not initialized.
embed not initialized.
decoder not initialized.
Traceback (most recent call last):
  File "E:\pycharm\pythonProject\.venv\测试.py", line 11, in <module>
    wavs = chat.infer(texts)
           ^^^^^^^^^^^^^^^^^
  File "E:\pycharm\pythonProject\.venv\Lib\site-packages\ChatTTS\core.py", line 220, in infer
    return next(res_gen)
           ^^^^^^^^^^^^^
  File "E:\pycharm\pythonProject\.venv\Lib\site-packages\ChatTTS\core.py", line 356, in _infer
    assert self.has_loaded(use_decoder=use_decoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by PandaXHFF** [comment]
> 请将 ffmpeg 放入 PATH 环境变量中。

panic: The handle is invalid.

goroutine 1 [running]:
rvcmd/console.init.0()
	rvcmd/console/console_windows.go:46 +0x1d4
download to local path E:\pycharm\pythonProject\.venv failed.
vocos not initialized.
gpt not initialized.
tokenizer not initialized.
embed not initialized.
decoder not initialized.
Traceback (most recent call last):
  File "E:\pycharm\pythonProject\.venv\测试.py", line 11, in <module>
    wavs = chat.infer(texts)
           ^^^^^^^^^^^^^^^^^
  File "E:\pycharm\pythonProject\.venv\Lib\site-packages\ChatTTS\core.py", line 220, in infer
    return next(res_gen)
           ^^^^^^^^^^^^^
  File "E:\pycharm\pythonProject\.venv\Lib\site-packages\ChatTTS\core.py", line 356, in _infer
    assert self.has_loaded(use_decoder=use_decoder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by PandaXHFF** [comment]
ffmpeg在环境变量中
