### ISSUE TITLE
遇到了一点问题，不是很明白

### ISSUE THREAD

**Issue by ooooolong** [2noise/ChatTTS#842]
我的error如下：
```
no GPU or NPU found, use CPU instead
text:   0%|          | 1/384(max) [00:00,  9.46it/s]We detected that you are passing `past_key_values` as a tuple of tuples. This is deprecated and will be removed in v4.47. Please convert your cache or use an appropriate `Cache` class (https://huggingface.co/docs/transformers/kv_cache#legacy-cache-format)
text:   1%|▏         | 5/384(max) [00:00, 16.68it/s]
code:   1%|          | 17/2048(max) [00:00, 31.02it/s]
Traceback (most recent call last):
  File "E:\24work\finalWork\ChatTTS\inference.py", line 29, in <module>
    torchaudio.save("output1.wav", torch.from_numpy(wavs[0]), 24000)
  File "E:\Anaconda\Lib\site-packages\torchaudio\_backend\utils.py", line 312, in save
    backend = dispatcher(uri, format, backend)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Anaconda\Lib\site-packages\torchaudio\_backend\utils.py", line 222, in dispatcher
    raise RuntimeError(f"Couldn't find appropriate backend to handle uri {uri} and format {format}.")
RuntimeError: Couldn't find appropriate backend to handle uri output1.wav and format None.
```
我有两点疑问：
1、
![image](https://github.com/user-attachments/assets/9cebe1ab-0703-4b7f-bcfe-89a53f9954e2)
wo'de我的compile参数已经设置成了True，为什么依然无法使用GPU呢？我的电脑是存在GPU的，难道compile参数不是用于启用GPU加速运算的吗？

2、即主要的Runtimeerror的报错！
略急！期待你的回复！感谢！！！

**Comment by ooooolong** [comment]
抱歉，出于我的疏忽，我的torch装的是2.5.1+cpu版本，但是关于runtimeerror我依然没解决

**Comment by fumiama** [comment]
安装ffmpeg相关库。

**Comment by yikchunnnn** [comment]
`GENERATING AUDIO RESPONSE
found invalid characters: {'!', '?', "'"}
text:   0%|▎                                                                                                                       | 1/384(max) [00:00,  7.03it/s]We detected that you are passing `past_key_values` as a tuple of tuples. This is deprecated and will be removed in v4.47. Please convert your cache or use an appropriate `Cache` class (https://huggingface.co/docs/transformers/kv_cache#legacy-cache-format)
text:   8%|█████████▎                                                                                                             | 30/384(max) [00:01, 20.05it/s]
code:  12%|██████████████▌                                                                                                      | 255/2048(max) [00:08, 30.50it/s]
Error generating audio: Couldn't find appropriate backend to handle uri response_audios/response_1736888433.wav and format None.
`

安裝了ffmpeg後還是這樣
還有別的dependency要安裝嗎
謝謝
