### ISSUE TITLE
运行webui.py 出现tool的问题

### ISSUE THREAD

**Issue by Fox-yang** [2noise/ChatTTS#844]
Traceback (most recent call last):
  File "/Users/fox/ChatTTS/examples/web/webui.py", line 13, in <module>
    from funcs import *
  File "/Users/fox/ChatTTS/examples/web/funcs.py", line 7, in <module>
    from tools.audio import float_to_int16, has_ffmpeg_installed, load_audio
ModuleNotFoundError: No module named 'tools'

**Comment by fumiama** [comment]
在项目根目录执行命令运行，不要在IDE直接点击运行，详见readme。
